basketapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import basketapp.views as basketapp

app_name = 'basket'

urlpatterns = [
    path('', basketapp.BasketList.as_view(), name='basket'),
    path('add/<int:pk>', basketapp.basket_add, name='basket_add'),
    path('order/', basketapp.order_send, name='order_send'),
    path('remove/<int:pk>', basketapp.basket_remove, name='basket_remove'),
    path('remove/', basketapp.basket_remove_all, name='basket_remove_all'),
]

userapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import userapp.views as userapp
import mainapp.urls

app_name = 'auth'

urlpatterns = [
    path('login/', userapp.LoginView.as_view(), name='login'),
    path('logout/', userapp.logout, name='logout'),
    path('register/', userapp.UserRegister.as_view(), name='register'),
    path('edit/<slug:slug>/', userapp.UserEdit.as_view(), name='edit'),
]

web_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

import mainapp.urls.products as products
import mainapp.urls.categories as categories
import userapp.urls as userapp
import basketapp.urls as basketapp
import adminapp.urls as adminapp
from mainapp.endpoints.products import ProductViewSet
from mainapp.endpoints.category import CategoryViewSet, category_list, category_detail
from basketapp.endpoints.basket import BasketViewSet
from userapp.endpoints.shop_user import ShopUserViewSet

schema_view = get_schema_view(title='Pastebin API')

router = DefaultRouter()
router.register('products', ProductViewSet)
router.register('categories', CategoryViewSet)
router.register('basket', BasketViewSet)
router.register('users', ShopUserViewSet)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('admin_custom/', include(adminapp)),
                  path('', include(products)),
                  path('catalog/', include(categories)),
                  path('auth/', include(userapp)),
                  path('basket/', include(basketapp)),
                  path('api/', include(router.urls)),
                  path('schema/', schema_view),
                  # path('pages/', include('django.contrib.flatpages.urls'),
                  # url(r'^catalog/', include(('mainapp.urls', 'catalog'), namespace='catalog')),
                  # url(r'^admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basketapp/models.py
from django.db import models

from django.db import models
from django.conf import settings
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='Дата и время покупки', auto_now_add=True)

    class Meta:
        unique_together = (
            'user',
            'product'
        )

    def _get_product_cost(self):
        return self.product.price * self.quantity

    product_cost = property(_get_product_cost)

    def _get_total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        _total_quantity = sum(list(map(lambda x: x.quantity, _items)))
        return _total_quantity

    total_quantity = property(_get_total_quantity)

    def __str__(self):
        return "Пользователь: {}; Товар: {}, кол-во: {}шт.".format(self.user.username, self.product.name, self.quantity)

    def _get_total_cost(self):
        _items = Basket.objects.filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

    total_cost = property(_get_total_cost)

basketapp/forms.py
from django import forms


# Проверка, что кол-во = целое число
def quantity_check(value):
    if value < 0:
        raise forms.ValidationError('Задано отрицательное число товаров: ', value)
    elif value == 0:
        raise forms.ValidationError('Число товаров не может быть нулевым', value)


class CartForm(forms.Form):
    quantity = forms.IntegerField(initial=1, required=False,
                                  label='количество', validators=[quantity_check]
                                  # widget=forms.widgets.TextInput(attrs={'class': 'form-control'} <input type=number>
                                  )

basketapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, get_list_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    FormView, CreateView, UpdateView,
    DeleteView, ListView, DetailView,
)
from django.contrib import messages

from . import forms
from basketapp.models import Basket
from mainapp.models import Product


# @login_required
# def basket(request):
#     basket_items = Basket.objects.filter(user=request.user).order_by('product__category')
#     return render(request, 'basketapp/basket.html', {'basket_items': basket_items})

class BasketList(LoginRequiredMixin, ListView):
    model = Basket
    template_name = 'basketapp/basket.html'
    context_object_name = 'basket_items'

    def get_queryset(self):
        queryset = self.model.objects.filter(user=self.request.user).order_by('product__category')
        return queryset


@login_required
def basket_add(request, pk):
    product = get_object_or_404(Product, id=pk)
    form = forms.CartForm(request.POST)
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product_detail', args=[product.name]))

    if form.is_valid():
        if form.cleaned_data.get('quantity'):
            quantity = int(form.cleaned_data.get('quantity'))
        else:
            quantity = 1
        # Проверка остатков на складе
        if product.quantity == 0:
            messages.add_message(request, messages.INFO, f'К сожалению, на данный момент товар отсутствует на складе')
        else:
            if quantity > product.quantity:
                messages.add_message(request, messages.INFO,
                                     f'На данный момент возможен заказ только {product.quantity}'
                                     f' единиц(-ы) товара!')
                quantity = product.quantity

            old_basket_item = Basket.objects.filter(user=request.user, product=product)
            if old_basket_item:
                old_basket_item[0].quantity += int(quantity)
                old_basket_item[0].save()
            else:
                new_basket_item = Basket(user=request.user, product=product)
                new_basket_item.quantity += int(quantity)
                new_basket_item.save()
            product.quantity = product.quantity - quantity
            product.save()
            messages.add_message(request, messages.INFO, 'Товар добавлен в корзину')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def order_send(request):
    return render(request, 'basketapp/order_form.html', {})


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove_all(request):
    Basket.objects.filter(user=request.user).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

basketapp/templates/basketapp/basket.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Корзина {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
{% endblock %}

{% block script %}
    <script>
        (function ($) {
            $(function () {
                $('#bot_name').effect('pulsate', 20000);
            });
        })(jQuery);
    </script>

{% endblock %}
{% block page_content %}

    {% if not basket_items %}

        <p>Сейчас ваша корзина пуста.

            Закажите товар по телефону 8(342)229-78-28 или перейдите к <a
                    href="{% url 'products:catalog' %}">каталогу</a>
        </p>

    {% else %}
        <div class="basket-page">

        <div class="basket_summary">
            В корзине <span>{{ basket_items.0.total_quantity }}</span> товара(-ов) общей стоимостью
            <span>{{ basket_items.0.total_cost|floatformat }}</span> руб.
        </div>
        <p id="bot_name">@CothyKitchenBot</p>
        <div class="bot_hover">
            <p>Заходите в наш чат-бот в Telegram и определите ближайший к Вам магазин прямо сейчас!</p>
            <p>Выберите удобный способ доставки и оплаты товара!</p>
        </div>
        <input type="button" id="send_order" value="Оформить заказ"
               onClick='alert("Функционал в разработке!!!")'>
        <!--onClick='location.href="{% url "basket:order_send" %}"'>-->

        {% for item in basket_items %}
            <div class="basket_item">
                <div class="product_image">
                    <p class="category_name">{{ item.product.short_desc|capfirst }}</p>
                    <img src="/media/{{ item.product.image.value }}" id="product_image"
                         alt="{{ item.product.short_desc }}">
                </div>
                <div class="product_item">
                    <p><span>Цена: </span>{{ item.product.price|floatformat }}&nbsp;руб.</p>
                    <p><span>Количество: </span>{{ item.quantity }}&nbsp;шт.</p>
                    <!--<label>Количество: <input type = "number" name ="{{item.pk}}" min ="0" value ="{{item.quantity}}"></label>-->
                    <input type="button" class="cart_del" value="Удалить"
                           onClick='location.href="{% url "basket:basket_remove" item.pk %}"'>
                </div>
            </div>

        {% endfor %}

    {% endif %}

<div class="basket-buttons">
    <input type="button" value="На главную"
           onClick='location.href="{% url "products:start_page" %}"'>

    <input type="button" value="Очистить корзину"
           onClick='location.href="{% url "basket:basket_remove_all" %}"'>

</div>
</div>

{% endblock %}

basketapp/templates/basketapp/order_form.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Корзина {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
{% endblock %}

{% block page_content %}

    <form action="#" class="order">
        <h2>Форма заказа:</h2>
        <br>
        <fieldset>
            <div class="form-group">
                <label class="form-field">
                    Покупатель:
                    <input type="radio" name="customer_type" value="individual" checked>Физическое лицо

                    <input type="radio" name="customer_type" value="entity">Юридическое лицо
                </label>
                <br><br>
                <label>

                    Контактное лицо:
                    <input type="text" name="customer_name" placeholder="{{ user.first_name }}">
                </label>
                <br><br>
                <label>
                    Телефон:
                    <input type="tel" name="customer_name" placeholder="{{ user.phone }}">
                </label>
                <br><br>
                <label>
                    Эл/почта:
                    <input type="email" name="customer_name" placeholder="{{ user.email }}">
                </label>
                <br><br>
                <label>Укажите дату доставки:
                    <input type="date" name="date"> </label>
                <br><br>

                <label>Выберите время доставки:
                    <input type="time" name="time"> </label>
                <br>
                <br>
                <label>
                    Способ доставки:
                    <input type="radio" name="delivery" value="curier" checked>Доставка курьером
                    <input type="radio" name="delivery" value="itself">Самовывоз
                </label>
                <div class="form-group">
                    <br>
                    <br>
                    <div class="button">
                        <button type="submit">Отправить</button>
                        <button type="reset">Очистить</button>
                    </div>
                    <br>
        </fieldset>
    </form>

{% endblock %}