adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

app_name = 'admin_custom'
urlpatterns = [
    path('', adminapp.admin_page, name='admin_page'),
    path('users/', adminapp.UserList.as_view(), name='users'),
    path('users/create/', adminapp.UserCreate.as_view(), name='user_create'),
    path('users/update/<slug:slug>/', adminapp.UserUpdate.as_view(),
         name='user_update'),
    path('users/delete/<slug:title>/', adminapp.user_delete,
         name='user_delete'),
    path('catalog/create/', adminapp.CategoryCreate.as_view(),
         name='category_create'),
    path('catalog/', adminapp.CategoryList.as_view(), name='category'),
    path('catalog/update/<slug:slug>/', adminapp.CategoryUpdate.as_view(),
         name='category_update'),
    path('catalog/delete/<slug:title>/', adminapp.category_delete,
         name='category_delete'),
    path('products/', adminapp.ProductList.as_view(), name='product_list'),
    path('<slug:slug>/products/', adminapp.ProductCategory.as_view(), name='category_products'),
    path('products/create/', adminapp.ProductCreate.as_view(),
         name='product_create'),
    path('products/update/<slug:slug>/', adminapp.ProductUpdate.as_view(),
         name='product_update'),
    path('products/delete/<slug:title>/', adminapp.product_delete,
         name='product_delete'),
]

userapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import userapp.views as userapp
import mainapp.urls

app_name = 'auth'

urlpatterns = [
    path('login/', userapp.LoginView.as_view(), name='login'),
    path('logout/', userapp.logout, name='logout'),
    path('register/', userapp.UserRegister.as_view(), name='register'),
    path('edit/<slug:slug>/', userapp.UserEdit.as_view(), name='edit'),
]

web_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

import mainapp.urls.products as products
import mainapp.urls.categories as categories
import userapp.urls as userapp
import basketapp.urls as basketapp
import adminapp.urls as adminapp
from mainapp.endpoints.products import ProductViewSet
from mainapp.endpoints.category import CategoryViewSet, category_list, category_detail
from basketapp.endpoints.basket import BasketViewSet
from userapp.endpoints.shop_user import ShopUserViewSet

schema_view = get_schema_view(title='Pastebin API')

router = DefaultRouter()
router.register('products', ProductViewSet)
router.register('categories', CategoryViewSet)
router.register('basket', BasketViewSet)
router.register('users', ShopUserViewSet)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('admin_custom/', include(adminapp)),
                  path('', include(products)),
                  path('catalog/', include(categories)),
                  path('auth/', include(userapp)),
                  path('basket/', include(basketapp)),
                  path('api/', include(router.urls)),
                  path('schema/', schema_view),
                  # path('pages/', include('django.contrib.flatpages.urls'),
                  # url(r'^catalog/', include(('mainapp.urls', 'catalog'), namespace='catalog')),
                  # url(r'^admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from userapp.models import ShopUser
from userapp.forms import ShopUserEditForm
from mainapp.models import Category, Product
from mainapp.forms import CategoryForm


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'
        widgets = {'avatar': forms.FileInput(attrs={'id': 'avatar'})}


class CategoryEditForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        field.help_text = ''

adminapp/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import (
    FormView, CreateView, UpdateView,
    DeleteView, ListView, DetailView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test

from userapp.models import ShopUser
from mainapp.models import Category, Product
from userapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from adminapp.forms import ShopUserAdminEditForm, CategoryEditForm, ProductEditForm
from mainapp.forms import ProductModelForm
from django.contrib import messages
from adminapp.mixins import SuperUserMixin


@user_passes_test(lambda u: u.is_superuser)
def admin_page(request):
    return render(request, 'adminapp/admin.html', {})


# CDUD-методы. Пользователи
class UserList(LoginRequiredMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'
    paginate_by = 2

    def get_queryset(self):
        queryset = ShopUser.objects.all().order_by('-is_active',
                                                   '-is_superuser', '-is_staff', 'username')
        return queryset


class UserCreate(LoginRequiredMixin, SuperUserMixin, CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'create.html'
    success_url = reverse_lazy('admin_custom:users')
    handle_no_permission = '/auth/login/'

    def get_context_data(self, **kwargs):
        context = super(UserCreate, self).get_context_data(**kwargs)
        context['title'] = 'Создание пользователя'
        context['url_cancel'] = 'admin_custom:users'
        context['OK_text'] = 'Создать'
        return context


class UserUpdate(LoginRequiredMixin, SuperUserMixin, UpdateView):
    model = ShopUser
    form_class = ShopUserAdminEditForm
    template_name = 'create.html'
    success_url = reverse_lazy('admin_custom:users')
    slug_field = 'username'

    def get_context_data(self, **kwargs):
        context = super(UserUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование пользователя'
        context['OK_text'] = 'Сохранить'
        context['url_cancel'] = 'admin_custom:users'
        return context


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, title):
    user = get_object_or_404(ShopUser, username=title)
    content = {'object_to_delete': user, 'title': 'Удаление пользователя', 'subject': 'пользователя',
               'name': user.username, 'part_name': 'Заблокированные пользователи',
               'url_cancel': request.META.get('HTTP_REFERER', 'admin_custom:users')}
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect("/admin_custom/users/")
    return render(request, 'delete.html', content)


# CDUD-методы. Категории

class CategoryList(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'adminapp/categories.html'
    context_object_name = 'objects'
    paginate_by = 2


class CategoryCreate(LoginRequiredMixin, SuperUserMixin, CreateView):
    model = Category
    form_class = CategoryEditForm
    template_name = 'create.html'
    success_url = reverse_lazy('admin_custom:category')

    def get_context_data(self, **kwargs):
        context = super(CategoryCreate, self).get_context_data(**kwargs)
        context['title'] = 'Создание категории'
        context['url_cancel'] = 'admin_custom:category'
        context['OK_text'] = 'Создать'
        return context


class CategoryUpdate(LoginRequiredMixin, SuperUserMixin, UpdateView):
    model = Category
    form_class = CategoryEditForm
    template_name = 'create.html'
    success_url = reverse_lazy('admin_custom:category')
    slug_field = 'name'

    def get_context_data(self, **kwargs):
        context = super(CategoryUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование категории'
        context['OK_text'] = 'Сохранить'
        context['url_cancel'] = 'admin_custom:category'
        return context


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, title):
    category = get_object_or_404(Category, name=title)
    content = {'object_to_delete': category, 'title': 'Удаление категории', 'subject': 'категории',
               'name': category.name, 'part_name': 'Архив', 'url_cancel': request.META.get('HTTP_REFERER',
                                                                                           'admin_custom:category')}
    if request.method == 'POST':
        category.is_active = False
        category.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return render(request, 'delete.html', content)


# Модель Product. CRUD


class ProductList(ListView):
    model = Product
    template_name = 'adminapp/product_list.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)
        # context['categories'] = Category.objects.all().order_by('name')
        context['active_categories'] = Category.objects.filter(id__in=Product.objects.filter(is_active=1).
                                                               values('category')).order_by('name')
        context['archive_categories'] = Category.objects.filter(id__in=Product.objects.filter(is_active=0).
                                                                values('category')).order_by('name')
        # Category.objects.filter(id__in=Product.objects.filter(is_active=1).values('category')).order_by('name')
        return context

    def get_queryset(self):
        queryset = Product.objects.all().order_by('category_id', 'price')
        return queryset


class ProductCategory(ListView):
    model = Product
    template_name = 'adminapp/products_category.html'
    context_object_name = 'products'
    slug_field = 'name'
    paginate_by = 2

    def get_queryset(self):
        queryset = Product.objects.filter(category__name=self.kwargs['slug']).order_by('price', 'name')
        return queryset


def products(request, title):
    category = get_object_or_404(Category, name=title)
    products_list = Product.objects.filter(category__name=title).order_by('name')
    content = {
        'category': category,
        'objects': products_list,
    }
    return render(request, 'adminapp/product_list.html', content)


class ProductCreate(LoginRequiredMixin, SuperUserMixin, CreateView):
    model = Product
    form_class = ProductModelForm
    template_name = 'create.html'
    success_url = reverse_lazy('admin_custom:product_list')

    def get_context_data(self, **kwargs):
        context = super(ProductCreate, self).get_context_data(**kwargs)
        context['title'] = 'Создание товара'
        context['url_cancel'] = 'admin_custom:product_list'
        context['OK_text'] = 'Добавить товар'
        return context


class ProductUpdate(LoginRequiredMixin, SuperUserMixin, UpdateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'create.html'
    success_url = reverse_lazy('admin_custom:product_list')
    slug_field = 'name'

    def get_context_data(self, **kwargs):
        context = super(ProductUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование товара'
        context['OK_text'] = 'Сохранить'
        context['url_cancel'] = 'admin_custom:product_list'
        return context


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, title):
    product = get_object_or_404(Product, name=title)
    content = {'object_to_delete': product, 'title': 'Удаление товара', 'subject': 'товара',
               'name': product.name, 'part_name': 'Архив', 'url_cancel': request.META.get('HTTP_REFERER',
                                                                                          'admin_custom:product_list')}
    if request.method == 'POST':
        product.is_active = False
        product.save()
        # return HttpResponseRedirect(request.META["HTTP_REFERER"])
        return HttpResponseRedirect("/admin_custom/products/category/" + product.category.name)
    return render(request, 'delete.html', content)

# def users(request):
#     users_list = ShopUser.objects.all().order_by('-is_active', \
#                                                  '-is_superuser', '-is_staff', 'username')
#     content = {
#         'objects': users_list
#     }
#     return render(request, 'adminapp/users.html', content)

# def user_create(request):
#
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#     if user_form.is_valid():
#         user_form.save()
#         return HttpResponseRedirect(reverse('admin_custom:users'))
#     else:
#         user_form = ShopUserRegisterForm()
#         content = {'update_form': user_form}
#         return render(request, 'adminapp/update.html', content)

# def get_absolute_url(self):
#     # return reverse('admin_custom:products', kwargs={'title': self.model.category.name})#
#     return reverse('products', kwargs={'title': self.form_class.category.name})

adminapp/templates/adminapp/admin.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Панель управления {% endblock %}

{% block menu %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
    <link rel="stylesheet" href="{% static 'adminapp/css/admin.css' %}">
{% endblock %}

{% block page_content %}
    {{ block.super }}
    <div class="admin">
        <h1>Управление интернет-магазином</h1>
        <!--<h2>Выберите раздел:</h2>-->
        <ul>
            <li><a href="{% url 'admin_custom:users' %}"> --> Пользователи</a></li>
            <li><a href="{% url 'admin_custom:category' %}"> --> Категории</a></li>
            <li><a href="{% url 'admin_custom:product_list' %}"> --> Товары</a></li>
        </ul>

    </div>
{% endblock %}

adminapp/templates/adminapp/categories.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Категории товара {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
    <link rel="stylesheet" href="{% static 'adminapp/css/admin.css' %}">
{% endblock %}

{% block menu %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block page_content %}
    {{ block.super }}

    <div class="categories_list">

        <input type="button" id="add_object" value="Добавить&nbsp;категорию"
               onClick='location.href="{% url "admin_custom:category_create" %}"'>

        {% for object in objects %}
            {% if object.is_active %}
                <div class="category_record">
                    <section class="object_name">
                        {{ object.name|title }}
                    </section>
                    <section class="object_desc">
                        {{ object.desc }}
                    </section>
                    <div class="category_actions">

                        <input type="button" value="Товары"
                               onClick='location.href="{% url "admin_custom:category_products" object.name %}"'>


                        <input type="button" value="Редактировать"
                               onClick='location.href="{% url "admin_custom:category_update" object.name %}"'>


                        <input type="button" value="Удалить"
                               onClick='location.href="{% url "admin_custom:category_delete" object.name %}"'>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        {% for object in objects %}
            {% if not object.is_active %}
                {% if forloop.first %}
                    <h2>Категории в архиве</h2>
                {% endif %}
                <div class="category_record">
                    <section class="object_name">
                        {{ object.name|title }}
                    </section>
                    <section class="object_desc">
                        {{ object.desc }}
                    </section>
                    <div class="category_actions">

                        <input type="button" value="Товары"
                               onClick='location.href="{% url "admin_custom:category_products" object.name %}"'>

                        <input type="button" value="Редактировать"
                               onClick='location.href="{% url "admin_custom:category_update" object.name %}"'>

                        <input type="button" value="Удалить"
                               onClick='location.href="{% url "admin_custom:category_delete" object.name %}"'>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <!--Постраничный переход -->
        {% if is_paginated %}
            <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'admin_custom:category' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'admin_custom:category' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
                <!--Перемещение по номерам страниц-->
                <div class="num_pages">
                    {% for pn in page_obj.paginator.page_range %}
                        {% if not forloop.first %}
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                        {% endif %}
                        {% if page_obj.number != pn %}
                            <a href="{% url 'admin_custom:category' %}?page={{ pn }}">
                        {% endif %}
                    {{ pn }}
                    {% if page_obj.number != pn %}
                        </a>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

adminapp/templates/adminapp/master.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block page_title %}
        {% endblock %}
    </title>

	{% block page_styles %}
        <link rel= "stylesheet" href= "{% static 'css/style.css' %}">
    {% endblock %}
</head>

<body>
    <div class="container">
        <div class="content">
            <header>
                <nav>
                    <ul class="menu">
                        <li><a href="{% url 'products:start_page'%}">Вернуться на сайт</a></li>
                        <li><a href="{% url 'admin:users'%}">Пользователи</a></li>
                        <li><a href="{% url 'admin:category'%}">Категории</a></li>
                        <li><a href="{% url 'admin:product_list'%}">Товары</a></li>
                    </ul>
                </nav>
            </header>
            <section>
                {% block page_content %}
                {% now "j F Y" %}
                {% endblock %}
            </section>
            {% block page_js %}
            {% endblock %}
        </div>
        <footer>
            <p>&copy;All rights reserved</p>
        </footer>
    </div>
</body>

</html>

adminapp/templates/adminapp/product.html
{% extends 'adminapp/master.html' %}

{% load staticfiles %}

{% block page_title %} Товары {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{%static 'adminapp/css/style.css' %}">
{% endblock %}

{% block page_content %}
{{ block.super }}

<div class = "products_list">
    <button class = "new_product">
    <a href = "{% url 'admin:product_create' category.name %}">
        Добавить новый товар
    </a>
    </button>
    {% for object in objects %}
        <div class="product_record">
            <img src = "{%static 'mainapp/img/default.jpg' %}"
            alt="{{object.name}}">
            <div class="product_name">
            {{object.name|title}}
        </div>
        <div class="product_actions">
            <button>
                <a href="{% url 'admin:product_read' object.name%}">
                    Подробнее
                </a>
            </button>
            <button>
                <a href="{% url 'admin:product_update' object.name %}">
                    Редактировать
                </a>
            </button>
            <button>
                <a href="{% url 'admin:product_delete' object.pk %}">
                    Удалить
                </a>
            </button>
        </div>
        <div class="summary">
            <b>Цена:</b>
            <p>{{object.price}} руб</p>
            <b>Количество:</b>
            <p>{{object.quantity}}</p>
            <b>Скидка:</b>
            <p>{{object.discount}}</p>
        </div>
        <div class="product_desc">
            {{object.short_desc|title}}
        </div>
    </div>
{% endfor%}
</div>

{% endblock %}

adminapp/templates/adminapp/product_list.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Товары {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
    <link rel="stylesheet" href="{% static 'adminapp/css/admin.css' %}">
{% endblock %}

{% block menu %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block page_content %}
    {{ block.super }}

    <div class="products_list">
        <div class="add_object">
            <input type="button" value="Добавить товар" id="add_object"
                   onClick='location.href="{% url "admin_custom:product_create" %}"'>
        </div>
        {% if active_categories %}
            <h2>Действующий каталог</h2>
        {% endif %}

        {% for category in active_categories %}
            <h2 class="category">Категория {{ category.name }}</h2>

            <div class="objects_list">
                {% for object in products %}
                    {% if object.is_active and object.category.id == category.id %}

                        <div class="object_data">
                            <section class="object_name">
                                {{ object.name|capfirst }}
                            </section>
                            <p><span>Цена: </span>
                                {{ object.price|floatformat }} руб.</p>
                            <p><span>Количество: </span>
                                {{ object.quantity }} шт.</p>
                            <p><span>Скидка: </span>
                                {{ object.discount|floatformat }}%</p>
                            <p><span>Краткое описание: </span>
                                {{ object.short_desc|capfirst }}</p>

                            <img src="/media/{{ object.image.value|default:'adminapp/img/default.jpg' }}"
                                 alt="{{ object.name }}" class="product_image">

                            <div class="product_actions">

                                <input type="button" value="Редактировать"
                                       onClick='location.href="{% url "admin_custom:product_update" object.name %}"'>

                                <input type="button" value="Удалить"
                                       onClick='location.href="{% url "admin_custom:product_delete" object.name %}"'>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}

        {% if archive_categories %}
            <h2>Архивный каталог</h2>
        {% endif %}

        {% for category in archive_categories %}
            <h2 class="category">Категория {{ category.name }}</h2>

            <div class="objects_list">
                {% for object in products %}
                    {% if not object.is_active and object.category.id == category.id %}

                        <div class="object_data">
                            <section class="object_name">
                                {{ object.name|capfirst }}
                            </section>
                            <p><span>Цена: </span>
                                {{ object.price|floatformat }} руб.</p>
                            <p><span>Количество: </span>
                                {{ object.quantity }} шт.</p>
                            <p><span>Скидка: </span>
                                {{ object.discount|floatformat }}%</p>
                            <p><span>Краткое описание: </span>
                                {{ object.short_desc|capfirst }}</p>

                            <img src="/media/{{ object.image.value|default:'adminapp/img/default.jpg' }}"
                                 alt="{{ object.name }}" class="product_image">

                            <div class="product_actions">

                                <input type="button" value="Редактировать"
                                       onClick='location.href="{% url "admin_custom:product_update" object.name %}"'>

                                <input type="button" value="Удалить"
                                       onClick='location.href="{% url "admin_custom:product_delete" object.name %}"'>
                            </div>

                        </div>
                        <br>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>

{% endblock %}

adminapp/templates/adminapp/products_category.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Товары {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
    <link rel="stylesheet" href="{% static 'adminapp/css/admin.css' %}">
{% endblock %}

{% block menu %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block page_content %}
    {{ block.super }}

    <div class="add_object">
        <input type="button" value="Добавить товар" id="add_object"
               class="product_image"
               onClick='location.href="{% url "admin_custom:product_create" %}"'>
    </div>

    <h2 class="category">Категория {{ products.0.category.name }}</h2>

    <div class="objects_list">
        {% for object in products %}
            <div class="object_data">
                <section class="object_name">
                    {{ object.name|capfirst }}
                </section>
                <p><span>Цена: </span>
                    {{ object.price|floatformat }} руб.</p>
                <p><span>Количество: </span>
                    {{ object.quantity }} шт.</p>
                <p><span>Скидка: </span>
                    {{ object.discount|floatformat }}%</p>
                <p><span>Краткое описание: </span>
                    {{ object.short_desc|capfirst }}</p>
                <div class="product_image">
                    <img src="/media/{{ object.image.value|default:'adminapp/img/default.jpg' }}"
                         alt="{{ object.name }}" id="product_image">
                </div>
                <div class="product_actions">
                    <input type="button" value="Редактировать"
                           onClick='location.href="{% url "admin_custom:product_update" object.name %}"'>

                    <input type="button" value="Удалить"
                           onClick='location.href="{% url "admin_custom:product_delete" object.name %}"'>
                </div>
            </div>
        {% endfor %}
    </div>
    <!--Постраничный переход -->
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'admin_custom:category_products'  products.0.category.name %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'admin_custom:category_products' products.0.category.name %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/master.html' %}

{% load staticfiles %}

{% block page_title %} Добавление пользователя {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{%static 'adminapp/css/style.css' %}">
{% endblock %}

{% block page_content %}
{{ block.super }}

<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}

    {% for err in forms.not_field_errors %}
    <div class="alert alert-danger" role="alert">
        <span>{{err}}</span>
    </div>
    {% endfor %}

    {% for field in form %}
    <div class="form-group">
        <label for="{{field.name}}">
            {{field.label}}
        </label>
        {{field}}

        {% for err in field.errors %}
        <small class="form-text">{{err}}</small>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit">Сохранить</button>
</form>



<button class =" btn btn - round form - control last ">
    <a href ="{% url 'admin:users' %}">
        К списку пользователей
    </a>
</button>


{% endblock %}