userapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import userapp.views as userapp
import mainapp.urls

app_name = 'auth'

urlpatterns = [
    path('login/', userapp.LoginView.as_view(), name='login'),
    path('logout/', userapp.logout, name='logout'),
    path('register/', userapp.UserRegister.as_view(), name='register'),
    path('edit/<slug:slug>/', userapp.UserEdit.as_view(), name='edit'),
]

web_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

import mainapp.urls.products as products
import mainapp.urls.categories as categories
import userapp.urls as userapp
import basketapp.urls as basketapp
import adminapp.urls as adminapp
from mainapp.endpoints.products import ProductViewSet
from mainapp.endpoints.category import CategoryViewSet, category_list, category_detail
from basketapp.endpoints.basket import BasketViewSet
from userapp.endpoints.shop_user import ShopUserViewSet

schema_view = get_schema_view(title='Pastebin API')

router = DefaultRouter()
router.register('products', ProductViewSet)
router.register('categories', CategoryViewSet)
router.register('basket', BasketViewSet)
router.register('users', ShopUserViewSet)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('admin_custom/', include(adminapp)),
                  path('', include(products)),
                  path('catalog/', include(categories)),
                  path('auth/', include(userapp)),
                  path('basket/', include(basketapp)),
                  path('api/', include(router.urls)),
                  path('schema/', schema_view),
                  # path('pages/', include('django.contrib.flatpages.urls'),
                  # url(r'^catalog/', include(('mainapp.urls', 'catalog'), namespace='catalog')),
                  # url(r'^admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError


# Create your models here.

def validate_positive(value):
    if value < 0:
        raise ValidationError('Цена должна быть задана положительным числом!', code='invalid')


class Category(models.Model):
    name = models.CharField(verbose_name='Наименование категории', max_length=200, unique=True)
    short_desc = models.CharField(verbose_name='Краткое описание', max_length=60,
                                  blank=True)
    desc = models.TextField(verbose_name='Подробное описание', blank=True)
    is_active = models.BooleanField(verbose_name='Запись активна', default=True)
    spec_discount = models.DecimalField(verbose_name='Специальная скидка', max_digits=4,
                                        decimal_places=2, default=0)
    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return 'catalog/%s' % self.name

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-is_active', 'name']
        verbose_name_plural = 'Categories'


class Product(models.Model):
    name = models.CharField(verbose_name='Наименование продукта', max_length=150, unique=True,
                            error_messages={'required': 'Укажите название товара'})
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # image = models.ImageField(upload_to='products_images', blank=True)
    image = models.ForeignKey(
        'images.Image',
        on_delete=models.SET_DEFAULT, default=10
    )
    short_desc = models.CharField(verbose_name='Краткое описание', max_length=60,
                                  blank=True)
    desc = models.TextField(verbose_name='Подробное описание', blank=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=8,
                                decimal_places=2, validators=[validate_positive], default=0)
    discount = models.DecimalField(verbose_name='Скидка', max_digits=4,
                                   decimal_places=2, default=0)
    is_active = models.BooleanField(verbose_name='Запись активна', default=True)

    quantity = models.PositiveIntegerField(verbose_name='Количество на складе', default=0)

    modified = models.DateTimeField(auto_now=True)

    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return f'catalog/{self.category.name}/{self.name}'

    def _get_min_price(self):
        result = Product.objects.aggregate(models.Min('price'))
        return result['price__min']

    min_price = property(_get_min_price)

    def _get_max_price(self):
        result = Product.objects.aggregate(models.Max('price'))
        return result['price__max']

    max_price = property(_get_max_price)

    def __str__(self):
        return "{} ({}р., {}шт.)".format(self.name, self.price, self.quantity)

    class Meta:
        ordering = ['-is_active', 'name', 'price']

mainapp/forms.py
from django import forms

from mainapp.models import Category, Product
from images.models import Image


class CategoryForm(forms.Form):
    name = forms.CharField(
        label='name',
        widget=forms.widgets.TextInput(attrs={'class': 'form-control'})

    )
    short_desc = forms.CharField(label='short_desc', required=False)
    desc = forms.CharField(label='desc', required=False, widget=forms.widgets.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Подробное описание'}
        )
                           )


class ProductForm(forms.Form):
    name = forms.CharField(
        label='name',
        widget=forms.widgets.TextInput(attrs={'class': 'form-control'})
    )

    category = forms.ModelChoiceField(
        queryset=Category.objects.all()
    )

    image = forms.ModelChoiceField(
        queryset=Image.objects.all()
    )

    short_desc = forms.CharField(label='short_desc', required=False)

    desc = forms.CharField(label='desc',
                           required=False,
                           widget=forms.widgets.Textarea(attrs={'class': 'form-control'}
                                                         )
                           )

    price = forms.DecimalField(
        label='price',
        required=False,
        widget=forms.widgets.NumberInput(
            attrs={'class': 'form-control'}
        )
    )

    discount = forms.DecimalField(
        label='discount',
        required=False,
        widget=forms.widgets.NumberInput(
            attrs={'class': 'form-control'}
        )
    )
    quantity = forms.IntegerField(
        label='quantity',
        required=False,
        widget=forms.widgets.NumberInput(
            attrs={'class': 'form-control'}
        )
    )


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'image', 'short_desc', 'desc', 'price', 'discount', 'quantity']
        labels = {
            'category': 'Категория',
            'image': 'Изображение'
        }
        help_texts = {
            'category': 'Выберите из списка:',
        }
        widgets = {'desc': forms.Textarea(attrs={'rows': 10, 'cols': 40})}

    # def __init__(self, *args, **kwargs):
    #     super(ProductModelForm, self).__init__(*args, **kwargs)
    # self.fields['name'].error_messages = {'required': 'Укажите название товара',
    #                                       'max_length': 'Название поле не должно превышать 150 символов'}


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'short_desc', 'desc']

mainapp/views/categories.py
import json
# import simplejson
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404, render_to_response
from django.template.loader import get_template
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.db import models
from django.views.generic import (
    TemplateView,
    FormView, CreateView, UpdateView,
    DeleteView, ListView, DetailView,
)
from django.views.generic.list import MultipleObjectMixin
from django.forms.models import modelformset_factory

from mainapp.models import Category, Product
from mainapp.forms import CategoryForm, CategoryModelForm
from django.contrib.auth.decorators import user_passes_test
from mainapp.mixins import SuperUserMixin

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required


# class CategoryCreate(View):
#     success_url = reverse_lazy('products:catalog')
#
#     def get(self, request):
#         form = CategoryForm()
#         return render(request, 'create.html', {'form': form})
#
#     def post(self, request):
#         form = CategoryForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             # return redirect('/')
#             return redirect(self.success_url)
#         return render(request, 'create.html', {'form': form})


class CategoryGenericCreate(SuperUserMixin, CreateView):
    model = Category
    form_class = CategoryModelForm
    template_name = 'create.html'
    success_url = reverse_lazy('products:catalog')

    def get_context_data(self, **kwargs):
        context = super(CategoryGenericCreate, self).get_context_data(**kwargs)
        context['title'] = 'Создание категории'
        context['url_cancel'] = 'products:catalog'
        context['OK_text'] = 'Добавить'
        return context


CategoryFormset = modelformset_factory(Category, form=CategoryModelForm,
                                       max_num=10, validate_max=True,
                                       help_texts={'name': 'Название категории должно быть уникальным'}, can_order=True,
                                       can_delete=True)


class CategoryFormSet(TemplateView):
    template_name = 'category_formset.html'
    formset = None

    def get(self, request, *args, **kwargs):
        self.formset = CategoryFormset()
        return super(CategoryFormSet, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CategoryFormSet, self).get_context_data(**kwargs)
        context['formset'] = self.formset
        context['title'] = 'Набор форм для Категории товара'
        return context

    def post(self, request, *args, **kwargs):
        self.formset = CategoryFormset(request.POST)
        if self.formset.is_valid():
            self.formset.save()
            return redirect('products:catalog')
        return super(CategoryFormSet, self).post(request, *args, **kwargs)


class CategoryGenericUpdate(SuperUserMixin, UpdateView):
    model = Category
    form_class = CategoryModelForm
    template_name = 'create.html'
    success_url = reverse_lazy('products:catalog')
    slug_field = 'name'

    def get_context_data(self, **kwargs):
        context = super(CategoryGenericUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование категории'
        context['url_cancel'] = 'products:catalog'
        context['OK_text'] = 'Сохранить'
        return context


class CategoryDetail(SuperUserMixin, DetailView):
    model = Category
    form_class = CategoryModelForm
    template_name = 'mainapp/categories.html'
    context_object_name = 'category'
    slug_field = 'name'

    def get_context_data(self, **kwargs):
        context = super(CategoryDetail, self).get_context_data(**kwargs)
        context['products'] = Product.objects.filter(category=self.object.id)
        context['min_price'] = context['products'].aggregate(models.Min('price'))['price__min']
        context['max_price'] = context['products'].aggregate(models.Max('price'))['price__max']
        return context


# class CategoryDelete(DeleteView):
#     model = Category
#     template_name = 'delete.html'
#     success_url = reverse_lazy('products:catalog')
#     slug_field = 'name'


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, title):
    category = get_object_or_404(Category, name=title)
    content = {'object_to_delete': category, 'title': 'Удаление категории', 'subject': 'категории',
               'name': category.name, 'part_name': 'Архив', 'url_cancel': request.META.get('HTTP_REFERER',
                                                                                           'products:catalog')}
    if request.method == 'POST':
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse('products:catalog'))
    return render(request, 'delete.html', content)


# def category_detail(request, slug):
#     cat = Category.objects.get(title=slug)
#     products = Product.objects.filter(category=cat.id)
#     return render(request, 'mainapp/categories.html',
#                   {'category': cat})

# def category_create(request):
#     form = CategoryForm(request.POST)
#
#     if request.method == 'POST':
#         if form.is_valid():
#             name = form.cleaned_data.get('name')
#             short_desc = form.cleaned_data.get('short_desc')
#             desc = form.cleaned_data.get('desc')
#
#         Category.objects.create(
#             name=name,
#             short_desc=short_desc,
#             desc=desc
#         )
#
#     return render(request, 'create.html', {'form': form})

def search_products(request):
    if request.method == 'POST':
        search_text = request.POST['search_text']
    else:
        search_text = ''
    if search_text != '':
        products = Product.objects.filter(short_desc__contains=search_text)
    return render_to_response('mainapp/components/ajax_search.html', {'objects': products,
                                                                      'search_url': 'categories:search_products'})

mainapp/templates/mainapp/catalog.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Catalog
{% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
{% endblock %}

{% block script %}
    <script src="{% static 'mainapp/js/ajax.js' %}"></script>
    <script>
        $(function () {
            $('#search').keyup(function () {
                $.ajax({
                    type: 'POST',
                    url: '/categories/search/',
                    data: {
                        'search_text': $('#search').val(),
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: searchSuccess,
                    datatype: 'html'
                });
            });
        });
    </script>
{% endblock %}

{% block page_content %}
    {{ block.super }}

    <div class="catalog-page">

        <div class="search_block">
            <h3>Поиск по категории</h3>
            {% csrf_token %}

            <input type="text" id="search" name="search"/>
        </div>
        <ul id="search_results">
        </ul>

        <div class="sale">
            {% for cat in categories %}
                <h2><a href="/{{ cat.get_absolute_url }}/" title={{ cat.descr }}>{{ cat.short_desc }}</a></h2>
            {% endfor %}
        </div>
        <main class="main">
            {% for product in products %}
                <figure class="item">
                    <a href="/{{ product.get_absolute_url }}/"> <img src="/media/{{ product.image.value }}"
                                                                     alt={{ product.short_desc|capfirst }}
                                                                             title={{ product.short_desc|capfirst }}
                                                                     height=300>
                        <br>
                        <p>{{ product.short_desc|capfirst }}</p>
                    </a>
                </figure>
            {% endfor %}
        </main>
        {% if products.paginator.num_pages > 1 %}
            <div class="paginator">
                {% if products.has_previous %}
                    <a href="{% url 'products:catalog' products.previous_page_number %}">
                        previous
                    </a>
                {% endif %}
                <span class="current">
        страница {{ products.number }} из
        {{ products.paginator.num_pages }}
        </span>
                {% if products.has_next %}
                    <a href="{% url 'products:catalog' products.next_page_number %}">
                        next
                    </a>
                {% endif %}
                <!--Перемещение по номерам страниц-->
                <div class="num_pages">
                    {% for pn in products.paginator.page_range %}
                        {% if not forloop.first %}
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                        {% endif %}

                        {% if products.number != pn %}
                            <a href="{% url 'products:catalog' pn %}">
                        {% endif %}
                    {{ pn }}
                    {% if products.number != pn %}
                        </a>
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="catalog-edit">
                    {% if user.is_authenticated and user.is_active and user.is_superuser %}
                        <a href="{% url 'categories:create' %}">Добавить категорию</a>
                        <a href="{% url 'categories:formsets' %}">Перейти к набору форм</a>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}
        

mainapp/templates/mainapp/categories.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Catalog
{% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
{% endblock %}

{% block script %}
    <script src="{% static 'mainapp/js/ajax.js' %}"></script>

    <script>
        $(function () {
            $('#search').keyup(function () {
                $.ajax({
                    type: 'POST',
                    url: '/catalog/products/search/',
                    data: {
                        'search_text': $('#search').val(),
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: searchSuccess,
                    datatype: 'html'
                });
            });

        });
    </script>
{% endblock %}

{% block page_content %}
    {{ block.super }}

    <div class="catalog-page">

        <div class="search_block">
            <h3>Поиск товара</h3>
            {% csrf_token %}

            <input type="text" id="search" name="search"/>
        </div>
        <ul id="search_results">
        </ul>

        <div class="category-head">
            <h1>{{ category.short_desc|capfirst }}</h1>
            <p>Цены в диапозоне: {{ min_price|floatformat }} - {{ max_price|floatformat }} руб.</p>
        </div>

        <main class="main">
            {% for product in products %}
                <figure class="item">
                    <!--<a href="/catalog/{{category.name}}/{{product.name}}/"> <img src="/media/{{product.image.value}}"-->
                    <a href="/{{ product.get_absolute_url }}/"> <img src="/media/{{ product.image.value }}"
                                                                     alt={{ product.short_desc|capfirst }}
                                                                             title={{ product.short_desc|capfirst }}
                                                                     height=300>
                        <br>
                        <p>{{ product.short_desc|capfirst }}</p>
                    </a>
                </figure>
            {% endfor %}
        </main>
        <div class="category-edit">
            {% if user.is_authenticated and user.is_active and user.is_superuser %}
                <a href="/catalog/update/{{ category.name }}/">Редактировать</a>
                <a href="/catalog/delete/{{ category.name }}/">Удалить</a>
                <a href="{% url 'products:create' %}">Добавить товар</a>
            {% endif %}
        </div>
    </div>

{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'master.html' %}

{% load static %}
{% load my_tags %}

{% block page_title %} Cozy kitchen {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'web_shop/style.css' %}">
    <link rel="stylesheet" href="{% static 'mainapp/css/jcarousel.css' %}">
    <link rel="stylesheet" href="{% static 'mainapp/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'mainapp/css/popup_window.css' %}">

{% endblock %}

{% block script %}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

    <script src="{% static 'mainapp/js/jquery.jcarousel.js' %}"></script>
    <script src="{% static 'mainapp/js/jcarousel.basic.js' %}"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script src="{% static 'mainapp/js/jquery.cookie.js' %}"></script>
    <script src="{% static 'mainapp/js/popup_window.js' %}"></script>

    <script>

        $(function () {

            <!--Заполнение корзины при перезагрузке страницы-->

            //localStorage.clear();

            if (localStorage.getItem('count')) {
                var count = localStorage.getItem('count');
                var product_key = 0;
                var price_key = 0;
                for (var i = 0; i <= count; i++) {
                    product_key = 'product_name_' + i;
                    price_key = 'product_price_' + i;

                    var NameValue = localStorage.getItem(product_key);

                    var PriceValue = localStorage.getItem(price_key);

                    var item = ($('<li/>', {
                        class: 'cartList__item'
                    }));
                    item.append($('<div/>', {
                        text: NameValue,
                        class: 'productName'
                    }));
                    item.append($('<div/>', {
                            text: PriceValue,
                            class: 'productPrice'
                        })
                    );

                    $('.cartList').append(item);
                }
                // Выводим общую сумму
                $('#general_sum').text(localStorage.getItem('sum'));
            }
            ;

            if (localStorage.getItem('sum')) {
                var sum = parseInt(localStorage.getItem('sum'));
            } else
                var sum = 0;

            $(function () {
                $('.jcarousel').jcarousel({
                    animation: {
                        duration: 900,
                        easing: 'linear',
                        complete: function () {
                        }
                    },
                    wrap: 'circular'
                })
            });

            $('.jcarousel').jcarouselAutoscroll({
                interval: 3000,
                target: '+=1',
                autostart: true
            });

            $('.carousel__item').draggable({
                opacity: 0.7,
                cursor: 'move',
                helper: 'clone'
            });

            $('#cartBlock').droppable({
                drop: function (event, ui) {
                    $(this).addClass('ui-state-highlight')
                    var item = ($('<li/>', {
                        class: 'cartList__item'
                    }));
                    item.append($('<div/>', {
                        text: ui['draggable'].find('.productName').eq(0).text(),
                        class: 'productName'
                    }));
                    item.append($('<div/>', {
                            <!--text: ui['draggable'].find('.productPrice').eq(0).text().split('.')[0] + ' руб.',-->
                            text: ui['draggable'].find('.productPrice').eq(0).text(),
                            class: 'productPrice'
                        })
                    );
                    <!--sum += parseInt(ui['draggable'].find('.productPrice').eq(0).text().split(' ')[0]);-->
                    sum += parseInt(ui['draggable'].find('.productPrice').eq(0).text());
                    $('#cartList').append(item);
                    $('#general_sum').text(sum);
                    if (localStorage.getItem('count')) {
                        var count = parseInt(localStorage.getItem('count'));
                    } else
                        var count = 0;
                    var product_key = 'product_name_' + count;
                    var price_key = 'product_price_' + count;

                    localStorage.setItem(product_key, ui['draggable'].find('.productName').eq(0).text());
                    localStorage.setItem(price_key, ui['draggable'].find('.productPrice').eq(0).text());
                    count += 1;
                    localStorage.setItem('count', String(count));
                    localStorage.setItem('sum', String(sum));


//        Переход по ссылке с методом
                    var product_id = parseInt(ui['draggable'].find('.productId').eq(0).text());
                    var url = '/basket/add/' + product_id;
                    $('#hide_button').on('click', location.replace(url));
                    $('#hide_button').click();
                }
            });
        });

    </script>

{% endblock %}

{% block page_content %}

    {{ block.super }}
    <div class="main-page">
        <main>
            <div class="about_company">
                <h1>{{ company.title|title }}</h1>
                <sector>{{ company.advertisement }}</sector>
            </div>

            <div class="spec_discount">
                {% offer as discount %}
                {% if discount %}
                    <p>Специальное предложение!!!</p>
                    <p>Только сегодня скидка на все товары от {{ discount }}!!! </p>
                {% endif %}
            </div>
            <div class="shopBlock">
                <div class="wrapper">
                    <div class="jcarousel-wrapper">
                        <div class="jcarousel">
                            <ul>
                                {% for product in products %}
                                    <li>
                                        <div class="carousel__item">
                                            <h3 class="productName">{{ product.short_desc|capfirst }}</h3>
                                            <h3 class="productId" style="display: none">{{ product.id }}</h3>
                                            <a href="/{{ product.get_absolute_url }}/">
                                                <img class="img" src="/media/{{ product.image.value }}"
                                                     alt={{ product.short_desc|capfirst }}
                                                             title={{ product.short_desc|capfirst }}>
                                            </a>
                                            <h3 class="productPrice">{{ product.price|floatformat }} руб.</h3>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>

                        </div>
                        <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                        <a href="#" class="jcarousel-control-next">&rsaquo;</a>
                    </div>
                </div>
                <div class="cartBlock" id="cartBlock">
                    <div class="cartImg">
                        <img src="{% static 'web_shop/img/basket.png' %}" alt="Cart">
                    </div>
                    <h1 class="cartTitle">Корзина</h1>
                    <ul class="cartList" id="cartList"></ul>
                    <p><b>Общая сумма:</b> <span id="general_sum">0</span> тыс.руб. </p>
                </div>
            </div>
        </main>
    </div>
    <script>
        {% if messages %}
            {% for message in messages %}
                alert('{{ message }}');
            {% endfor %}
        {% endif %}
    </script>

    <!--Всплывающее окно при первой загрузке сайта-->
    {% if not user.is_authenticated %}
        <div id="pp">
            <div class="pp-header">
                <h3>Приветствуем Вас на сайте Cozy Kitchen!!!</h3>
            </div>
            <div class="pp-content">
                <div class="pp-content-main">

                    <h4>*Товар дня*</h4>
                    <p> Только сегодня
                        {% for cat in categories %}
                            {% if cat.spec_discount %}
                                скидка на все <span>{{ cat.short_desc|upper }}</span> до
                                <span>{{ cat.spec_discount|floatformat }}%</span>
                            {% endif %}
                        {% endfor %}
                    </p>
                </div>

            </div>
            <div class="pp-footer">
                <p><a href="{% url 'auth:register' %}">Зарегистрируйтесь </a> и получите индивидуальную скидку на весь
                    модельный ряд!!!</p>
            </div>
            <div class="btn btn-blob">&times;</div>
        </div>

        <div id="pp-bg"></div>

    {% endif %}

    <button class="hide_button"></button>

{% endblock %}