adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

app_name = 'admin_custom'
urlpatterns = [
    path('', adminapp.admin_page, name='admin_page'),
    path('users/', adminapp.UserList.as_view(), name='users'),
    path('users/create/', adminapp.UserCreate.as_view(), name='user_create'),
    path('users/update/<slug:slug>/', adminapp.UserUpdate.as_view(),
         name='user_update'),
    path('users/delete/<slug:title>/', adminapp.user_delete,
         name='user_delete'),
    path('catalog/create/', adminapp.CategoryCreate.as_view(),
         name='category_create'),
    path('catalog/', adminapp.CategoryList.as_view(), name='category'),
    path('catalog/update/<slug:slug>/', adminapp.CategoryUpdate.as_view(),
         name='category_update'),
    path('catalog/delete/<slug:title>/', adminapp.category_delete,
         name='category_delete'),
    path('products/', adminapp.ProductList.as_view(), name='product_list'),
    path('<slug:slug>/products/', adminapp.ProductCategory.as_view(), name='category_products'),
    path('products/create/', adminapp.ProductCreate.as_view(),
         name='product_create'),
    path('products/update/<slug:slug>/', adminapp.ProductUpdate.as_view(),
         name='product_update'),
    path('products/delete/<slug:title>/', adminapp.product_delete,
         name='product_delete'),
]

basketapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import basketapp.views as basketapp

app_name = 'basket'

urlpatterns = [
    path('', basketapp.BasketList.as_view(), name='basket'),
    path('add/<int:pk>', basketapp.basket_add, name='basket_add'),
    path('order/', basketapp.order_send, name='order_send'),
    path('remove/<int:pk>', basketapp.basket_remove, name='basket_remove'),
    path('remove/', basketapp.basket_remove_all, name='basket_remove_all'),
]

userapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
import userapp.views as userapp
import mainapp.urls

app_name = 'auth'

urlpatterns = [
    path('login/', userapp.LoginView.as_view(), name='login'),
    path('logout/', userapp.logout, name='logout'),
    path('register/', userapp.UserRegister.as_view(), name='register'),
    path('edit/<slug:slug>/', userapp.UserEdit.as_view(), name='edit'),
]

web_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

import mainapp.urls.products as products
import mainapp.urls.categories as categories
import userapp.urls as userapp
import basketapp.urls as basketapp
import adminapp.urls as adminapp
from mainapp.endpoints.products import ProductViewSet
from mainapp.endpoints.category import CategoryViewSet, category_list, category_detail
from basketapp.endpoints.basket import BasketViewSet
from userapp.endpoints.shop_user import ShopUserViewSet

schema_view = get_schema_view(title='Pastebin API')

router = DefaultRouter()
router.register('products', ProductViewSet)
router.register('categories', CategoryViewSet)
router.register('basket', BasketViewSet)
router.register('users', ShopUserViewSet)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('admin_custom/', include(adminapp)),
                  path('', include(products)),
                  path('catalog/', include(categories)),
                  path('auth/', include(userapp)),
                  path('basket/', include(basketapp)),
                  path('api/', include(router.urls)),
                  path('schema/', schema_view),
                  # path('pages/', include('django.contrib.flatpages.urls'),
                  # url(r'^catalog/', include(('mainapp.urls', 'catalog'), namespace='catalog')),
                  # url(r'^admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_shop/templates/includes/form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for err in forms.not_field_errors %}
        <div class="alert alert-danger" role="alert">
            <span>{{ err }}</span>
        </div>
    {% endfor %}

    <div class="form-group">
        {% for field in form %}

            <div class="form-field">
                <label for="{{ field.name }}">
                    {{ field.label }}:
                </label>
                {{ field }}
            </div>
        {% endfor %}

    <div class="OK_button">
        <input type="submit" value="{{ OK_text }}">
        <!--<input type="button"  value="Отмена"-->
        <!--onClick='location.href="{{url_cancel}}"'>-->
    </div>
    </div>
    {% for field in form %}
        {% if field.errors|length > 0 %}
            {% for err in field.errors %}
                <small class="form-text">{{ err }}</small>
            {% endfor %}
        {% endif %}
    {% endfor %}
</form>

web_shop/templates/includes/inc_menu.html
{% load static %}
{% load cart %}
<nav>
    <ul class="menu">
        <li><a href="{% url 'products:start_page' %}">Главная</a></li>
        <li><a href="{% url 'products:catalog' %}" class="expand-catalog">Каталог</a>
        </li>
        <li><a href="{% url 'products:contacts' %}">Контакты</a></li>

        <!--<svg aria-hidden="true" class="icon icon-basket">-->
        <!--<use xlink:href="{}"></use>-->
        <!--</svg>-->
        <!--<span class="elem-cart__num ng-binding ng-hide" data-ng-bind="cartData.model.totalBasketQuantity" data-ng-show="cartData.model.totalBasketQuantity > 0">0</span>-->
        <!--Корзина-->
        <!--</a>-->
        {% if user.is_superuser %}
            <li><a href="{% url 'admin_custom:admin_page' %}">Настройка</a></li>
        {% endif %}
        <li class="basket">
            <a href="{% url 'basket:basket' %}"><img src="{% static 'web_shop/img/basket.png' %}" alt="Корзина"
                                                     class="basket"></a>
        </li>
        {% if user.is_authenticated %}
            <li id="total_quantity">
                <span class="text-inner">{{ user.id|total_quantity }}</span>
            </li>
        {% endif %}

    </ul>
    <ul class="menu user">
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit' user.username %}">
                    {{ user.username|default:'User' }}
                </a>
            </li>
        {% endif %}
        {% if user.is_authenticated %}
            <li class="menu user">
                <a href="{% url 'auth:logout' %}">Выход</a>
                {% else %}
                <a href="{% url 'auth:login' %}" class="menu entrance">Вход</a>
            </li>

        {% endif %}
    </ul>
</nav>